### ISSUE TITLE
Any plans for a server side CSGO-AC?

### ISSUE THREAD

**Issue by SteveBox0** [ekknod/CSGO-AC#1]
Any plans for a server side CSGO-AC?

**Comment by ekknod** [comment]
Lets see if CS:GO gets engine update, then i concider of writing some Anti-Cheat plugin for it

**Comment by mrc4tt** [comment]
Any update on this? ^

**Comment by ekknod** [comment]
> Any update on this? ^

No updates. I have couple ideas which i would like to give a try with a serverside AC at some point
